2025-08-02 23:57:35,504 ERROR: Exception on /register [POST] [in C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\wtforms\validators.py", line 401, in __call__
    import email_validator
ModuleNotFoundError: No module named 'email_validator'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\app\routes.py", line 62, in register
    if form.validate_on_submit():
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask_wtf\form.py", line 86, in validate_on_submit
    return self.is_submitted() and self.validate(extra_validators=extra_validators)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\wtforms\form.py", line 330, in validate
    return super().validate(extra)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\wtforms\form.py", line 147, in validate
    if not field.validate(self, extra):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\wtforms\fields\core.py", line 234, in validate
    stop_validation = self._run_validation_chain(form, chain)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\wtforms\fields\core.py", line 254, in _run_validation_chain
    validator(form, self)
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\wtforms\validators.py", line 403, in __call__
    raise Exception(
Exception: Install 'email_validator' for email validation support.
2025-08-03 00:03:31,584 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:45]
2025-08-03 00:05:40,108 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:45]
2025-08-03 00:08:01,419 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:45]
2025-08-03 00:09:29,840 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:45]
2025-08-05 16:22:45,305 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:45]
2025-08-05 16:25:16,097 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:45]
2025-08-05 16:26:02,950 ERROR: Exception on / [POST] [in C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\app\routes.py", line 24, in index
    return redirect(url_for('/index'))
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\helpers.py", line 232, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint '/index'. Did you mean 'index' instead?
2025-08-05 16:26:41,280 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:45]
2025-08-07 11:39:57,853 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:45]
2025-08-07 11:41:45,070 ERROR: Exception on /index [GET] [in C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\app\routes.py", line 26, in index
    return render_template('index.html' , title='Home Page', posts=posts, form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\jinja2\environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\HP3\Desktop\MicroBlog\app\templates\index.html", line 17, in template
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endif'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-08-07 11:45:16,321 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:45]
2025-08-07 12:08:07,938 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:45]
2025-08-07 15:37:55,865 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:45]
